baseurl = "/personal"
languageCode = "en-us"
title = "A Personal page"
theme = "xmin"
googleAnalytics = "UA-35860999-1"
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
preserveTaxonomyNames = true
footnotereturnlinkcontents = "↩"

[permalinks]
    post = "/post/:year/:month/:day/:slug/"
    note = "/note/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[params]
    description = "A website built through Hugo and blogdown."
    footer = "&copy; perforb 2018"
